# Generated by Django 5.0.7 on 2024-07-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
