# Generated by Django 5.0.7 on 2024-07-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_data_password_alter_data_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
